development:
  book: 'law713'
  coming_soon:
    - '4-rails'
    - '4-loops'
  draft:
  assignment_unlock_week: 0
  # require_login: true

test:
  book: 'law713'
  assignment_unlock_week: 2
  # require_login: true

production:
  book: <%= ENV['BOOK'] %>
  assignment_unlock_week: <%= ENV['BOOK_ASSIGNMENT_UNLOCK_WEEK'] %>
  require_login: <%= ENV["BOOK_REQUIRE_LOGIN"].present? %>
  coming_soon:
    - '4-rails'
    - '4-loops'
  draft:
    - '2-html'
    - '3-ruby'
