development:
  book: <%= ENV['BOOK'] || 'law713 '%>
  assignment_unlock_week: <%= ENV['BOOK_ASSIGNMENT_UNLOCK_WEEK'] || 10 %>
  require_login: <%= ENV["BOOK_REQUIRE_LOGIN"].present? || false %>
  draft:

test:
  book: 'law713'
  assignment_unlock_week: 2
  # require_login: true

production:
  book: <%= ENV['BOOK'] %>
  assignment_unlock_week: <%= ENV['BOOK_ASSIGNMENT_UNLOCK_WEEK'] %>
  require_login: <%= ENV["BOOK_REQUIRE_LOGIN"].present? %>
  coming_soon:
    - '4-rails'
  draft:
