development:
  book: 'law713'
  number: 'LAWSTUDY-713'
  name: "Introduction to Software Development"
  domain: "http://workbook.dev"
  canvas_course_id: "18760000000064832"
  school: "NU"
  assignment_unlock_week: 2
  # require_login: true

test:
  book: 'law713'
  number: 'LAWSTUDY-713'
  name: "Introduction to Software Development"
  domain: "http://workbook.dev"
  canvas_course_id: "18760000000064832"
  school: "NU"
  assignment_unlock_week: 2

production:
  book: 'law713'
  number: 'LAWSTUDY-713'
  name: "Introduction to Software Development"
  domain: "http://workbook.dev"
  canvas_course_id: "18760000000064832"
  school: "NU"
  assignment_unlock_week: 2
  
